version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: guinchaedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
