
create table car (
                     car_drive_type smallint check (car_drive_type between 0 and 3),
                     eletric_parking_brake boolean not null,
                     tow_hook_present boolean not null,
                     id bigint not null,
                     tow_instructions varchar(255),
                     primary key (id)
);

create table motorcycle (
                            is_electric boolean not null,
                            tow_strap_points integer not null,
                            id bigint not null,
                            primary key (id)
);

create table request (
                         client_id bigint,
                         created_at timestamp(6),
                         id bigint generated by default as identity,
                         tow_truck_driver_id bigint,
                         updated_at timestamp(6),
                         drop_address varchar(255),
                         message varchar(255),
                         pickup_address varchar(255),
                         status varchar(255) check (status in ('PENDING','ASSIGNED','ACCEPTED','COMPLETED')),
                         primary key (id)
);

create table request_model_tried_drivers (
                                             request_model_id bigint not null,
                                             tried_drivers bigint
);

create table roles (
                       created_at timestamp(6) not null,
                       id bigint generated by default as identity,
                       updated_at timestamp(6),
                       name varchar(255) unique,
                       primary key (id)
);

create table token (
                       created_at timestamp(6),
                       expires_at timestamp(6),
                       id bigint generated by default as identity,
                       user_id bigint not null,
                       validated_at timestamp(6),
                       token varchar(255),
                       primary key (id)
);

create table tow_truck (
                           load_capacity integer not null,
                           platform_length float(53) not null,
                           driver_id bigint,
                           id bigint not null,
                           primary key (id)
);

create table tow_truck_driver (
                                  is_assigned boolean not null,
                                  is_available boolean not null,
                                  id bigint not null,
                                  cnh_number varchar(255),
                                  primary key (id)
);

create table user_address (
                              id bigint generated by default as identity,
                              numero bigint,
                              bairro varchar(255),
                              cep varchar(255),
                              cidade varchar(255),
                              complemento varchar(255),
                              estado varchar(255),
                              rua varchar(255),
                              primary key (id)
);

create table user_roles (
                            role_id bigint not null,
                            user_id bigint not null
);

create table users (
                       account_locked boolean not null,
                       birth_date date,
                       enabled boolean not null,
                       latitude float(53),
                       longitude float(53),
                       adress_id bigint unique,
                       created_at timestamp(6) not null,
                       id bigint generated by default as identity,
                       updated_at timestamp(6),
                       cpf varchar(255) unique,
                       email varchar(255) unique,
                       first_name varchar(255),
                       last_name varchar(255),
                       password varchar(255),
                       phone_number varchar(255),
                       primary key (id)
);

create table vehicle (
                         weight integer not null,
                         year integer not null,
                         id bigint generated by default as identity,
                         user_id bigint,
                         brand_name varchar(255),
                         license_plate varchar(255),
                         model varchar(255),
                         primary key (id)
);

alter table if exists car
    add constraint fk_car_vehicle
        foreign key (id)
            references vehicle;

alter table if exists motorcycle
    add constraint fk_motorcycle_vehicle
        foreign key (id)
            references vehicle;

alter table if exists request
    add constraint fk_request_users
        foreign key (client_id)
            references users;

alter table if exists request
    add constraint fk_request_tow_truck_driver
        foreign key (tow_truck_driver_id)
            references tow_truck_driver;

alter table if exists request_model_tried_drivers
    add constraint  fk_request_model_tried_drivers_request
        foreign key (request_model_id)
            references request;

alter table if exists token
    add constraint fk_request_token_users
        foreign key (user_id)
            references users;

alter table if exists tow_truck
    add constraint  fk_tow_truck_tow_truck_driver
        foreign key (driver_id)
            references tow_truck_driver;

alter table if exists tow_truck
    add constraint fk_tow_truck_vehicle
        foreign key (id)
            references vehicle;

alter table if exists tow_truck_driver
    add constraint fk_tow_truck_driver_users
        foreign key (id)
            references users;

alter table if exists user_roles
    add constraint fk_user_roles_roles
        foreign key (role_id)
            references roles;

alter table if exists user_roles
    add constraint fk_user_roles_users
        foreign key (user_id)
            references users;

alter table if exists users
    add constraint fk_users_user_address
        foreign key (adress_id)
            references user_address;

alter table if exists vehicle
    add constraint fk_vehicle_users
        foreign key (user_id)
            references users;