spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1/
