spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guinchae
    username: tales
    password: tales
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: devs
    password: devs
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: kFgzqK6fxcMn3lsBx8Q4hLtHn5+L+haQ7rcVn/IM6EY=
      expiration: 4320000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088